language: node_js

node_js:
  - "5"

script:
  - npm run lint
  - if [ "$SAUCE_ACCESS_KEY" ]; then npm run test:sauce; else npm run test; fi

after_success:
  - npm install coveralls lcov-result-merger
  - $(npm bin)/lcov-result-merger './coverage/*/lcov.info' | $(npm bin)/coveralls
  - ./scripts/deploy.sh
